{{- range .Values.jvb.replicas }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi.jvb.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/jvb-name: {{ .name }}
    {{- include "jitsi.jvb.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/jvb-name: {{ .name }}
      {{- include "jitsi.jvb.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/jvb-name: {{ .name }}
        {{- include "jitsi.jvb.selectorLabels" $ | nindent 8 }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jitsi.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          envFrom:
          - configMapRef:
              name: {{ include "jitsi.fullname" $ }}
          - secretRef:
              name: {{ include "jitsi.fullname" $ }}
          env:
          - name: JVB_PORT
            value: {{ .udp | quote }}
          - name: JVB_TCP_PORT
            value: {{ .tcp | quote }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.jvb.image.repository }}:{{ $.Values.jvb.image.tag }}"
          imagePullPolicy: {{ $.Values.jvb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: tcp
              containerPort: {{ .tcp }}
              protocol: TCP
            - name: udp
              containerPort: {{ .udp }}
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /about/health
              port: http
          readinessProbe:
            httpGet:
              path: /about/health
              port: http
          resources:
            {{- toYaml $.Values.jvb.resources | nindent 12 }}
      {{- with $.Values.jvb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.jvb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.jvb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}