apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi.prosody.fullname" . }}
  labels:
    {{- include "jitsi.prosody.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5280
      targetPort: bosh
      protocol: TCP
      name: bosh
    - port: 5222
      targetPort: xmpp
      protocol: TCP
      name: xmpp
    - port: 5347
      targetPort: components
      protocol: TCP
      name: components
  selector:
    {{- include "jitsi.prosody.selectorLabels" . | nindent 4 }}
