# Default values for jitsi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

web:
  name: web
  image:
    repository: jitsi/web
    tag: latest
    pullPolicy: Always

  replicaCount: 3

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      # kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    host: meet.example.com
    tls:
      secretName: chart-example-tls



prosody:
  name: prosody
  image:
    repository: jitsi/prosody
    tag: latest
    pullPolicy: Always

  replicaCount: 1

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}


jicofo:
  name: jicofo
  image:
    repository: jitsi/jicofo
    tag: latest
    pullPolicy: Always

  replicaCount: 1

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

jibri:
  name: jibri
  image:
    repository: jitsi/jibri
    tag: latest
    pullPolicy: Always

  replicaCount: 1

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

jvb:
  name: jvb
  image:
    repository: jitsi/jvb
    tag: latest
    pullPolicy: Always

  replicas:
    - name: jvb1
      tcp: 30001
      udp: 30001
    - name: jvb2
      tcp: 30002
      udp: 30002
    - name: jvb3
      tcp: 30003
      udp: 30003
    - name: jvb4
      tcp: 30004
      udp: 30004
    - name: jvb5
      tcp: 30005
      udp: 30005
    - name: jvb6
      tcp: 30006
      udp: 30006

  resources:
    limits:
    #   cpu: 100m
      memory: 5Gi
    requests:
      cpu: 6
      memory: 3Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000





